//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LT_ServerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablePriorityView
    {
        public string TestBenchID { get; set; }
        public string TestBenchName { get; set; }
        public string TableName { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public int ID { get; set; }
        public string PriorityName { get; set; }
        public string Frequency { get; set; }
        public string DBName { get; set; }
    }
}
